### ISSUE TITLE
No working 

### ISSUE THREAD

**Issue by FreeEagles** [saqura/xmppwb#1]
**Hi I try pip3 install xmppwb  and look install xmppwb**

> `Requirement already satisfied (use --upgrade to upgrade): xmppwb in /usr/local/lib/python3.4/dist-packages
> Requirement already satisfied (use --upgrade to upgrade): aiohttp in /usr/local/lib/python3.4/dist-packages (from xmppwb)
> Requirement already satisfied (use --upgrade to upgrade): pyyaml in /usr/local/lib/python3.4/dist-packages (from xmppwb)
> Requirement already satisfied (use --upgrade to upgrade): slixmpp in /usr/local/lib/python3.4/dist-packages (from xmppwb)
> Requirement already satisfied (use --upgrade to upgrade): chardet in /usr/local/lib/python3.4/dist-packages (from aiohttp->xmppwb)
> Requirement already satisfied (use --upgrade to upgrade): aiodns>=1.0 in /usr/local/lib/python3.4/dist-packages (from slixmpp->xmppwb)
> Requirement already satisfied (use --upgrade to upgrade): pyasn1 in /usr/local/lib/python3.4/dist-packages (from slixmpp->xmppwb)
> Requirement already satisfied (use --upgrade to upgrade): pyasn1-modules in /usr/local/lib/python3.4/dist-packages (from slixmpp->xmppwb)
> Requirement already satisfied (use --upgrade to upgrade): pycares>=1.0.0 in /usr/local/lib/python3.4/dist-packages (from aiodns>=1.0->slixmpp->xmppwb)`

**But by example I do xmppwb --help and I got:**
`File "/usr/local/bin/xmppwb", line 9, in <module>
    load_entry_point('xmppwb==0.2.5', 'console_scripts', 'xmppwb')()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python3.4/dist-packages/xmppwb/core.py", line 17, in <module>
    from xmppwb.bridge import XMPPWebhookBridge, InvalidConfigError
  File "/usr/local/lib/python3.4/dist-packages/xmppwb/bridge.py", line 87
    async def handle_outgoing(self, outgoing_webhook, msg):
            ^
SyntaxError: invalid syntax
`
Any ideas how to solve that

**Comment by saqura** [comment]
As mentioned in the readme xmppwb requires Python 3.5+ but you seem to have Python 3.4. So you need to upgrade Python first.
