### ISSUE TITLE
Issues with dependency slixmpp

### ISSUE THREAD

**Issue by blubbi321** [saqura/xmppwb#11]
Hey there,
currently struggeling with getting everything to run ;)

One thing that hit me (and which I could resolve) was that the dependency to slixmpp will cause an 
`ERROR    'XEP_0045' object has no attribute 'joinMUC'`
when slixmpp is > 1.1 (current stable is 1.2.1)

Thanks for your effort in creating this bridge! Hope you can fix this issue.

**Comment by saqura** [comment]
Thanks for notifying me! It seems that the API of slixmpp changed with the recent version. This should be fixed now in version 0.5.0 (304a65a) of xmppwb, which is also available on PyPi. You can upgrade using `pip install --upgrade xmppwb`.

Let me know if there are any remaining problems. I haven't tested the bridge with slixmpp 1.2.1 yet.

**Comment by blubbi321** [comment]
Thanks for fixing it so quickly! :-)
