### ISSUE TITLE
bridge only works one way

### ISSUE THREAD

**Issue by ghost** [saqura/xmppwb#5]
Hello.

I have xmppbw up and running but bridging only seems to work in one direction. I can enter some text in the rocketchat webbrowser and the text is shown in the conference configured. But when i enter some text via xabber (android) in the very same conference the text is not shown in the browser window in rocketchat. Firewall is disabled and i am able to connect on port 443. Here is the debug output:

```
04-20:43:37 INFO     poll 299999.109 ms took 128825.052 ms: 1 events
04-20:43:37 DEBUG    --> Received message from XMPP by rocketbridge@conference.dings.meine-oma.de/himbeere: hallo!
04-20:43:37 DEBUG    <-- Sending outgoing webhook. (from 'rocketbridge@conference.dings.meine-oma.de/himbeere')
04-20:43:37 DEBUG    Get address info chat.meine-oma.de:443, type=<SocketKind.SOCK_STREAM: 1>
04-20:43:37 DEBUG    Getting address info chat.meine-oma.de:443, type=<SocketKind.SOCK_STREAM: 1> took 0.933 ms: [(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('138.201.43.25', 443))]
04-20:43:37 DEBUG    poll 171169.313 ms took 0.615 ms: 1 events
04-20:43:37 DEBUG    connect <socket.socket fd=8, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('0.0.0.0', 0)> to ('138.201.43.25', 443)
04-20:43:37 DEBUG    poll 171167.081 ms took 0.016 ms: 1 events
04-20:43:37 DEBUG    <_SelectorSslTransport fd=8 read=idle write=<idle, bufsize=0>> starts SSL handshake
04-20:43:37 DEBUG    poll 171165.378 ms took 1.729 ms: 1 events
04-20:43:37 DEBUG    poll 171162.243 ms took 0.120 ms: 1 events
04-20:43:37 DEBUG    <_SelectorSslTransport fd=8 read=polling write=<idle, bufsize=0>>: SSL handshake took 4.4 ms
04-20:43:37 DEBUG    <ssl.SSLSocket fd=8, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('138.201.43.25', 54502), raddr=('138.201.43.25', 443)> connected to chat.meine-oma.de:443: (<_SelectorSslTransport fd=8 read=polling write=<idle, bufsize=0>>, <aiohttp.parsers.StreamProtocol object at 0x7f5b5dfe47b8>)
04-20:43:37 DEBUG    poll 171159.968 ms took 616.760 ms: 1 events
04-20:44:08 INFO     poll 30720.661 ms took 30758.418 ms: timeout
04-20:44:28 INFO     poll 139781.744 ms took 19886.611 ms: 1 events
04-20:44:28 DEBUG    poll 119892.160 ms took 0.021 ms: 1 events
04-20:43:37 DEBUG    --> Received message from XMPP by rocketbridge@conference.dings.meine-oma.de/himbeere: hallo!
04-20:43:37 DEBUG    <-- Sending outgoing webhook. (from 'rocketbridge@conference.dings.meine-oma.de/himbeere')
04-20:43:37 DEBUG    Get address info chat.meine-oma.de:443, type=<SocketKind.SOCK_STREAM: 1>
04-20:43:37 DEBUG    Getting address info chat.meine-oma.de:443, type=<SocketKind.SOCK_STREAM: 1> took 0.933 ms: [(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('138.201.43.25', 443))]
04-20:43:37 DEBUG    poll 171169.313 ms took 0.615 ms: 1 events
04-20:43:37 DEBUG    connect <socket.socket fd=8, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('0.0.0.0', 0)> to ('138.201.43.25', 443)
04-20:43:37 DEBUG    poll 171167.081 ms took 0.016 ms: 1 events
04-20
```

thanks again.

**Comment by saqura** [comment]
The incoming webhook settings in RocketChat include a curl example: Can you confirm that the webhook works by executing this example? (It starts with `curl -X POST ...`)

**Comment by ghost** [comment]
I have this working now too. I had to use a real user in rocketchat for the "post as" user in incoming webhook. It was rocket.cat. That does not seem to work. 

Aside from that. Can you explain this three settings?

```
        override_username: "{nick}"
        message_template: "_{msg}_"
        use_attachment_formatting: true
```

It changes obiously the look of the message in the rocketchat channel?

And bye the way. Big thanks for your work.

**Comment by saqura** [comment]
> I had to use a real user in rocketchat for the "post as" user in incoming webhook. It was rocket.cat. That does not seem to work.

This is strange, since I successfully use the rocket.cat user. If the curl example doesn't work with rocket.cat you might want to raise an issue on the [Rocket.Chat repo](https://github.com/RocketChat/Rocket.Chat).

> Can you explain this three settings?

All the settings are explained in [CONFIGURATION.rst](https://github.com/saqura/xmppwb/blob/master/CONFIGURATION.rst#the-outgoing_webhooks-section-of-a-bridge). `message_template: "_{msg}_"` makes the message appear with _italic formatting_ (RocketChat uses Markdown syntax, so the underscores make it italic). `use_attachment_formatting` is a special option that can be used with RocketChat. It makes the messages look a bit different. You can experiment with it to see which version you prefer.

> Big thanks for your work.

You are welcome!
